FROM ubuntu:latest
RUN /usr/bin/apt-get update -y
RUN /usr/bin/apt-get install -y apt-utils
RUN /usr/bin/apt-get install -y default-jdk
RUN /usr/bin/apt-get install -y tar
RUN /usr/bin/apt-get install -y wget
RUN cd /tmp
RUN /usr/bin/wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.tar.gz
RUN mkdir /opt/tomcat
RUN tar xf apache-tomcat-9.0.39.tar.gz -C /opt/tomcat --strip-components=1
RUN useradd tomcat
RUN chgroup -R tomcat /opt/tomcat
RUN chgroup -R g=x+r /opt/tomcat
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh","run"]
